version: "3.8"

services:

  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 7s
      timeout: 3s
      retries: 10

  db:
    image: postgres:15.1-alpine

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 7s
      timeout: 3s
      retries: 10

  app:
    build: .
    tty: true
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
#
  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO -P eventlet
    depends_on:
      - redis
      - app
    env_file:
      - .env

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app
    env_file:
      - .env
